[package]
name = "dialogue-editor"
version = "1.0.0"
description = "A dialogue editor for GameMaker projects"
authors = [""]
edition = "2021"

[lib]
name = "dialogue_editor_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = { version = "2", features = ["watch"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
